// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aylkfgmvncucsojrclbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bGtmZ212bmN1Y3NvanJjbGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNjA5ODAsImV4cCI6MjA4ODYzNjk4MH0.FNa9_WLKlYPyVAGtOavOJzIzBdIvBYqz_PL7c9-h7xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});